package gpemlc;

import net.sf.jclec.util.random.AbstractRandGenFactory;
import net.sf.jclec.util.random.IRandGen;
import net.sf.jclec.util.random.Ranecu;

/**
 * Ranecu factory.
 * 
 * @author Sebastian Ventura
 */

public final class RanecuFactory2 extends AbstractRandGenFactory
{
	/////////////////////////////////////////////////////////////////
	// --------------------------------------- Serialization constant
	/////////////////////////////////////////////////////////////////
	
	/** Generated by Eclipse */
	
	private static final long serialVersionUID = -5925252460325410373L;

	/////////////////////////////////////////////////////////////////
	// ------------------------------------------------- Constructors
	/////////////////////////////////////////////////////////////////
	
	/**
	 * Empty (default) constructor.
	 */
	
	public RanecuFactory2() 
	{
		super();
	}

	/////////////////////////////////////////////////////////////////
	// ----------------------------------------------- Public methods 
	/////////////////////////////////////////////////////////////////
	
	// IRandGenFactory interface 
	
	/**
	 * {@inheritDoc}
	 */
	
	public final IRandGen createRandGen() 
	{
		return new Ranecu(seedGenerator.nextSeed(), seedGenerator.nextSeed());
	}
	
	public final IRandGen createRandGen(int seed1, int seed2) 
	{
		return new Ranecu(seed1, seed2);
	}
}
