package net.sf.jclec.listind;

import net.sf.jclec.ISpecies;
import net.sf.jclec.base.AbstractRecombinator;


/**
 * MultipListIndividual (and subclasses) specific recombinator.  
 * 
 * @author Jose M. Moyano
 * @author Sebastian Ventura
 */

public abstract class MultipListRecombinator extends AbstractRecombinator
{
	
	/////////////////////////////////////////////////////////////////
	// ------------------------------------------ Operation variables
	/////////////////////////////////////////////////////////////////

	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = -2482775303204486624L;
	
	/** Individual species (taked from execution context) */
	protected transient MultipListSpecies species;
	
	/** Set ppl=2 */
	
	@Override
	protected void setPpl() 
	{
		this.ppl = 2;
	}

	/** Set spl=2 */

	@Override
	protected void setSpl() 
	{
		this.spl = 2;
	}

	/////////////////////////////////////////////////////////////////
	// ------------------------------------------------- Constructors
	/////////////////////////////////////////////////////////////////

	/**
	 * Empty (default) constructor.
	 */
	public MultipListRecombinator() 
	{
		super();
	}

	/**
	 * {@inheritDoc}
	 */
	
	@Override
	protected void prepareRecombination() 
	{
		ISpecies species = context.getSpecies();
		if (species instanceof MultipListSpecies) {
			// Set individuals speciess
			this.species = (MultipListSpecies) species;
		}
		else {
			throw new IllegalStateException("Invalid population species");
		}		
	}
	
}
