package net.sf.jclec.stringtree;

import net.sf.jclec.IFitness;
import net.sf.jclec.IIndividual;

import net.sf.jclec.base.AbstractIndividual;
import net.sf.jclec.binarray.BinArrayIndividual;

import org.apache.commons.lang.builder.EqualsBuilder;

/**
 * Individual with a byte array as genotype.
 *  
 * @author Sebastian Ventura
 */

@SuppressWarnings("deprecation")
public class StringTreeIndividual extends AbstractIndividual<String> 
{
	/////////////////////////////////////////////////////////////////
	// --------------------------------------- Serialization constant
	/////////////////////////////////////////////////////////////////

	/** Generated by eclipse */
	
	private static final long serialVersionUID = 6227386750669278917L;

	/////////////////////////////////////////////////////////////////
	// ------------------------------------------------- Constructors
	/////////////////////////////////////////////////////////////////
	
	/**
	 * Empty constructor
	 */
	
	public StringTreeIndividual() 
	{
		super();
	}

	/**
	 * Constructor that sets individual genotype.
	 * 
	 * @param genotype Individual genotype
	 */
	
	public StringTreeIndividual(String genotype) 
	{
		super(genotype);
	}

	/**
	 * Constructor that sets individual genotype and fitness.
	 * 
	 * @param genotype Individual genotype
	 * @param fitness  Individual fitness
	 */
	
	public StringTreeIndividual(String genotype, IFitness fitness) 
	{
		super(genotype, fitness);
	}

	/////////////////////////////////////////////////////////////////
	// ----------------------------------------------- Public methods
	/////////////////////////////////////////////////////////////////
		
	// IIndividual methods
		
	/**
	 * {@inheritDoc}
	 */
		
	public IIndividual copy() 
	{
		// Allocate a copy of genotype
		String gother = new String(genotype);

		// Create new individuals, then return it
		if (fitness != null) {
			return new StringTreeIndividual(gother, fitness.copy());			
		}
		else {
			return new StringTreeIndividual(gother);			
		}
	}

	
	/**
	 * {@inheritDoc}
	 */
	
	@Override
	public boolean equals(Object other) 
	{
		if (other instanceof StringTreeIndividual) {
			StringTreeIndividual baother = (StringTreeIndividual) other;
			EqualsBuilder eb = new EqualsBuilder();
			eb.append(genotype, baother.genotype);
			eb.append(fitness, baother.fitness);
			return eb.isEquals();
		}
		else {
			return false;
		}
	}

	@Override
	public double distance(IIndividual arg0) {
		// TODO Auto-generated method stub
		return 0;
	}
	
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return genotype;
	}
}
